language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    # - php: 5.5
    - php: 5.6
    # - php: 7.0
    # - php: 7.1

before_install:
  - phpenv config-rm xdebug.ini
  # - composer self-update not needed
  # - composer
  - which composer
  - file `which composer`
  - cat `which composer`
  # - php -d memory_limit=-1 /home/travis/.phpenv/shims/composer
  # - composer -d memory_limit=-1

install:
  - composer install

script:
  # - ./vendor/bin/simple-phpunit
  # this checks that the source code follows the Symfony Code Syntax rules
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -vvv --stop-on-violation
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -vvv -- .
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -vvv -- Controller
  # this checks that the YAML config files contain no syntax errors
  # - ./bin/console lint:yaml config
  # - ./bin/console lint:yaml @CodeExplorerBundle
  # this checks that the Twig template files contain no syntax errors
  # - ./bin/console lint:twig templates @CodeExplorerBundle
  # this checks that the XLIFF translations contain no syntax errors
  # - ./bin/console lint:xliff templates
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  # - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock

# inspirated from symfony/symfony-demo
